// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrEb6-jYL5UEVvr4dGKGlNHlPJX0aSwnk',
    appId: '1:975135211957:web:8ea5a006fd1c8c73ac19fc',
    messagingSenderId: '975135211957',
    projectId: 'selo-dev-1749f',
    authDomain: 'selo-dev-1749f.firebaseapp.com',
    storageBucket: 'selo-dev-1749f.firebasestorage.app',
    measurementId: 'G-DR4EK4YWLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzLojnHPVft52m4ZV4S-Hzirn5keMTBU0',
    appId: '1:1007242542755:android:62bc2c6d52fb8ed1d80916',
    messagingSenderId: '1007242542755',
    projectId: 'selloa',
    storageBucket: 'selloa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF3vs52taaORusg5c5wvciGXoPtjz98Dk',
    appId: '1:1007242542755:ios:d1a75ec5fc01f743d80916',
    messagingSenderId: '1007242542755',
    projectId: 'selloa',
    storageBucket: 'selloa.firebasestorage.app',
    iosBundleId: 'com.selo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-lwxNgbv3MI55zQhRsKpGTydSMMWq1gM',
    appId: '1:975135211957:ios:3f356e4dba5f0c20ac19fc',
    messagingSenderId: '975135211957',
    projectId: 'selo-dev-1749f',
    storageBucket: 'selo-dev-1749f.firebasestorage.app',
    iosBundleId: 'com.selo.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrEb6-jYL5UEVvr4dGKGlNHlPJX0aSwnk',
    appId: '1:975135211957:web:7be899187c668aa3ac19fc',
    messagingSenderId: '975135211957',
    projectId: 'selo-dev-1749f',
    authDomain: 'selo-dev-1749f.firebaseapp.com',
    storageBucket: 'selo-dev-1749f.firebasestorage.app',
    measurementId: 'G-9Z524W9XX2',
  );
}