import 'package:selo/core/models/category.dart';

final List<PlaceCategory> regions = [
  PlaceCategory(
    id: 0,
    name: 'Актобе',
    subcategories: [
      PlaceCategory(id: 0, name: 'Астанинский район'),
      PlaceCategory(id: 1, name: 'Алматинский район'),
    ],
  ),
  PlaceCategory(
    id: 1,
    name: 'Алматы',
    subcategories: [
      PlaceCategory(id: 0, name: 'Алатауский район'),
      PlaceCategory(id: 1, name: 'Алмалинский район'),
      PlaceCategory(id: 2, name: 'Ауэзовский район'),
      PlaceCategory(id: 3, name: 'Бостандыкский район'),
      PlaceCategory(id: 4, name: 'Жетысуский район'),
      PlaceCategory(id: 5, name: 'Медеуский район'),
      PlaceCategory(id: 6, name: 'Наурызбайский район'),
      PlaceCategory(id: 7, name: 'Турксибский район'),
    ],
  ),
  PlaceCategory(
    id: 2,
    name: 'Астана',
    subcategories: [
      PlaceCategory(id: 0, name: 'Алматинский район'),
      PlaceCategory(id: 1, name: 'Байконурский район'),
      PlaceCategory(id: 2, name: 'Есильский район'),
      PlaceCategory(id: 3, name: 'Нуринский район'),
      PlaceCategory(id: 4, name: 'Сарыаркинский район'),
    ],
  ),
  PlaceCategory(
    id: 3,
    name: 'Караганда',
    subcategories: [
      PlaceCategory(id: 0, name: 'Алихана Бокейханова район'),
      PlaceCategory(id: 1, name: 'Казыбекбийский район'),
    ],
  ),
  PlaceCategory(
    id: 4,
    name: 'Шымкент',
    subcategories: [
      PlaceCategory(id: 0, name: 'Абайский район'),
      PlaceCategory(id: 1, name: 'Аль-Фарабийский район'),
      PlaceCategory(id: 2, name: 'Енбекшинский район'),
      PlaceCategory(id: 3, name: 'Каратауский район'),
      PlaceCategory(id: 4, name: 'Туранский район'),
    ],
  ),

  PlaceCategory(
    id: 5,
    name: 'Абайская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Абайский район'),
      PlaceCategory(id: 1, name: 'Аксуатский район'),
      PlaceCategory(id: 2, name: 'Аягозский район'),
      PlaceCategory(id: 3, name: 'Бескарагайский район'),
      PlaceCategory(id: 4, name: 'Бородулихинский район'),
      PlaceCategory(id: 5, name: 'Жанасемейский район'),
      PlaceCategory(id: 6, name: 'Жарминский район'),
      PlaceCategory(id: 7, name: 'Кокпектинский район'),
      PlaceCategory(id: 8, name: 'Маканчинский район'),
      PlaceCategory(id: 9, name: 'Урджарский район'),
    ],
  ),
  PlaceCategory(
    id: 6,
    name: 'Акмолинская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Аккольский район'),
      PlaceCategory(id: 1, name: 'Аршалынский район'),
      PlaceCategory(id: 2, name: 'Астраханский район'),
      PlaceCategory(id: 3, name: 'Атбасарский район'),
      PlaceCategory(id: 4, name: 'Биржан‐сал район'),
      PlaceCategory(id: 5, name: 'Буландынский район'),
      PlaceCategory(id: 6, name: 'Бурабайский район'),
      PlaceCategory(id: 7, name: 'Егиндыкольский район'),
      PlaceCategory(id: 8, name: 'Ерейментауский район'),
      PlaceCategory(id: 9, name: 'Есильский район'),
      PlaceCategory(id: 10, name: 'Жаксынский район'),
      PlaceCategory(id: 11, name: 'Жаркаинский район'),
      PlaceCategory(id: 12, name: 'Зерендинский район'),
      PlaceCategory(id: 13, name: 'Коргалжынский район'),
      PlaceCategory(id: 14, name: 'Сандыктауский район'),
      PlaceCategory(id: 15, name: 'Целиноградский район'),
      PlaceCategory(id: 16, name: 'Шортандинский район'),
    ],
  ),
  PlaceCategory(
    id: 7,
    name: 'Актюбинская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Айтекебийский район'),
      PlaceCategory(id: 1, name: 'Алгинский район'),
      PlaceCategory(id: 2, name: 'Байганинский район'),
      PlaceCategory(id: 3, name: 'Иргизский район'),
      PlaceCategory(id: 4, name: 'Каргалинский район'),
      PlaceCategory(id: 5, name: 'Мартукский район'),
      PlaceCategory(id: 6, name: 'Мугалжарский район'),
      PlaceCategory(id: 7, name: 'Темирский район'),
      PlaceCategory(id: 8, name: 'Уилский район'),
      PlaceCategory(id: 9, name: 'Хобдинский район'),
      PlaceCategory(id: 10, name: 'Хромтауский район'),
      PlaceCategory(id: 11, name: 'Шалкарский район'),
    ],
  ),
  PlaceCategory(
    id: 8,
    name: 'Алматинская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Балхашский район'),
      PlaceCategory(id: 1, name: 'Енбекшиказахский район'),
      PlaceCategory(id: 2, name: 'Жамбылский район'),
      PlaceCategory(id: 3, name: 'Илийский район'),
      PlaceCategory(id: 4, name: 'Карасайский район'),
      PlaceCategory(id: 5, name: 'Кегенский район'),
      PlaceCategory(id: 6, name: 'Райымбекский район'),
      PlaceCategory(id: 7, name: 'Талгарский район'),
      PlaceCategory(id: 8, name: 'Уйгурский район'),
    ],
  ),
  PlaceCategory(
    id: 9,
    name: 'Атырауская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Жылыойский район'),
      PlaceCategory(id: 1, name: 'Индерский район'),
      PlaceCategory(id: 2, name: 'Исатайский район'),
      PlaceCategory(id: 3, name: 'Кзылкогинский район'),
      PlaceCategory(id: 4, name: 'Курмангазинский район'),
      PlaceCategory(id: 5, name: 'Макатский район'),
      PlaceCategory(id: 6, name: 'Махамбетский район'),
    ],
  ),
  PlaceCategory(
    id: 10,
    name: 'Восточно-Казахстанская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Алтайский район'),
      PlaceCategory(id: 1, name: 'Глубоковский район'),
      PlaceCategory(id: 2, name: 'Зайсанский район'),
      PlaceCategory(id: 3, name: 'Катон-Карагайский район'),
      PlaceCategory(id: 4, name: 'Курчумский район'),
      PlaceCategory(id: 5, name: 'Маркакольский район'),
      PlaceCategory(id: 6, name: 'Самарский район'),
      PlaceCategory(id: 7, name: 'Тарбагатайский район'),
      PlaceCategory(id: 8, name: 'Уланский район'),
      PlaceCategory(id: 9, name: 'Улькен Нарынский район'),
      PlaceCategory(id: 10, name: 'Шемонаихинский район'),
    ],
  ),
  PlaceCategory(
    id: 11,
    name: 'Жамбылская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Байзакский район'),
      PlaceCategory(id: 1, name: 'Жамбылский район'),
      PlaceCategory(id: 2, name: 'Жуалынский район'),
      PlaceCategory(id: 3, name: 'Кордайский район'),
      PlaceCategory(id: 4, name: 'Меркенский район'),
      PlaceCategory(id: 5, name: 'Мойынкумский район'),
      PlaceCategory(id: 6, name: 'Район имени Т. Рыскулова'),
      PlaceCategory(id: 7, name: 'Сарысуский район'),
      PlaceCategory(id: 8, name: 'Таласский район'),
      PlaceCategory(id: 9, name: 'Шуский район'),
    ],
  ),
  PlaceCategory(
    id: 12,
    name: 'Жетысуская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Аксуский район'),
      PlaceCategory(id: 1, name: 'Алакольский район'),
      PlaceCategory(id: 2, name: 'Ескельдинский район'),
      PlaceCategory(id: 3, name: 'Каратальский район'),
      PlaceCategory(id: 4, name: 'Кербулакский район'),
      PlaceCategory(id: 5, name: 'Коксуский район'),
      PlaceCategory(id: 6, name: 'Панфиловский район'),
      PlaceCategory(id: 7, name: 'Саркандский район'),
    ],
  ),
  PlaceCategory(
    id: 13,
    name: 'Западно-Казахстанская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Акжаикский район'),
      PlaceCategory(id: 1, name: 'Байтерекский район'),
      PlaceCategory(id: 2, name: 'Бокейординский район'),
      PlaceCategory(id: 3, name: 'Бурлинский район'),
      PlaceCategory(id: 4, name: 'Жангалинский район'),
      PlaceCategory(id: 5, name: 'Жанибекский район'),
      PlaceCategory(id: 6, name: 'Казталовский район'),
      PlaceCategory(id: 7, name: 'Каратобинский район'),
      PlaceCategory(id: 8, name: 'Сырымский район'),
      PlaceCategory(id: 9, name: 'Таскалинский район'),
      PlaceCategory(id: 10, name: 'Теректинский район'),
      PlaceCategory(id: 11, name: 'Чингирлауский район'),
    ],
  ),
  PlaceCategory(
    id: 14,
    name: 'Карагандинская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Абайский район'),
      PlaceCategory(id: 1, name: 'Актогайский район'),
      PlaceCategory(id: 2, name: 'Бухар-Жырауский район'),
      PlaceCategory(id: 3, name: 'Каркаралинский район'),
      PlaceCategory(id: 4, name: 'Нуринский район'),
      PlaceCategory(id: 5, name: 'Осакаровский район'),
      PlaceCategory(id: 6, name: 'Шетский район'),
    ],
  ),
  PlaceCategory(
    id: 15,
    name: 'Костанайская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Алтынсаринский район'),
      PlaceCategory(id: 1, name: 'Амангельдинский район'),
      PlaceCategory(id: 2, name: 'Аулиекольский район'),
      PlaceCategory(id: 3, name: 'Беимбета Майлина район'),
      PlaceCategory(id: 4, name: 'Денисовский район'),
      PlaceCategory(id: 5, name: 'Джангельдинский район'),
      PlaceCategory(id: 6, name: 'Житикаринский район'),
      PlaceCategory(id: 7, name: 'Камыстинский район'),
      PlaceCategory(id: 8, name: 'Карабалыкский район'),
      PlaceCategory(id: 9, name: 'Карасуский район'),
      PlaceCategory(id: 10, name: 'Костанайский район'),
      PlaceCategory(id: 11, name: 'Мендыкаринский район'),
      PlaceCategory(id: 12, name: 'Наурзумский район'),
      PlaceCategory(id: 13, name: 'Сарыкольский район'),
      PlaceCategory(id: 14, name: 'Узункольский район'),
      PlaceCategory(id: 15, name: 'Фёдоровский район'),
    ],
  ),
  PlaceCategory(
    id: 16,
    name: 'Кызылординская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Аральский район'),
      PlaceCategory(id: 1, name: 'Жалагашский район'),
      PlaceCategory(id: 2, name: 'Жанакорганский район'),
      PlaceCategory(id: 3, name: 'Казалинский район'),
      PlaceCategory(id: 4, name: 'Кармакшинский район'),
      PlaceCategory(id: 5, name: 'Сырдарьинский район'),
      PlaceCategory(id: 6, name: 'Шиелийский район'),
    ],
  ),
  PlaceCategory(
    id: 17,
    name: 'Мангистауская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Бейнеуский район'),
      PlaceCategory(id: 1, name: 'Каракиянский район'),
      PlaceCategory(id: 2, name: 'Мангистауский район'),
      PlaceCategory(id: 3, name: 'Мунайлинский район'),
      PlaceCategory(id: 4, name: 'Тупкараганский район'),
    ],
  ),
  PlaceCategory(
    id: 18,
    name: 'Павлодарская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Актогайский район'),
      PlaceCategory(id: 1, name: 'Баянаульский район'),
      PlaceCategory(id: 2, name: 'Железинский район'),
      PlaceCategory(id: 3, name: 'Иртышский район'),
      PlaceCategory(id: 4, name: 'Теренкольский район'),
      PlaceCategory(id: 5, name: 'Аккулинский район'),
      PlaceCategory(id: 6, name: 'Майский район'),
      PlaceCategory(id: 7, name: 'Павлодарский район'),
      PlaceCategory(id: 8, name: 'Успенский район'),
      PlaceCategory(id: 9, name: 'Щербактинский район'),
    ],
  ),
  PlaceCategory(
    id: 19,
    name: 'Северо-Казахстанская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Айыртауский район'),
      PlaceCategory(id: 1, name: 'Акжарский район'),
      PlaceCategory(id: 2, name: 'Аккайынский район'),
      PlaceCategory(id: 3, name: 'Есильский район'),
      PlaceCategory(id: 4, name: 'Жамбылский район'),
      PlaceCategory(id: 5, name: 'Магжана Жумабаева район'),
      PlaceCategory(id: 6, name: 'Кызылжарский район'),
      PlaceCategory(id: 7, name: 'Мамлютский район'),
      PlaceCategory(id: 8, name: 'Габита Мусрепова район'),
      PlaceCategory(id: 9, name: 'Тайыншинский район'),
      PlaceCategory(id: 10, name: 'Тимирязевский район'),
      PlaceCategory(id: 11, name: 'Уалихановский район'),
      PlaceCategory(id: 12, name: 'Шал Акына район'),
    ],
  ),
  PlaceCategory(
    id: 20,
    name: 'Туркестанская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Байдибекский район'),
      PlaceCategory(id: 1, name: 'Жетысайский район'),
      PlaceCategory(id: 2, name: 'Казыгуртский район'),
      PlaceCategory(id: 3, name: 'Келесский район'),
      PlaceCategory(id: 4, name: 'Мактааральский район'),
      PlaceCategory(id: 5, name: 'Ордабасынский район'),
      PlaceCategory(id: 6, name: 'Отырарский район'),
      PlaceCategory(id: 7, name: 'Сайрамский район'),
      PlaceCategory(id: 8, name: 'Сарыагашский район'),
      PlaceCategory(id: 9, name: 'Сауранский район'),
      PlaceCategory(id: 10, name: 'Сузакский район'),
      PlaceCategory(id: 11, name: 'Толебийский район'),
      PlaceCategory(id: 12, name: 'Тюлькубасский район'),
      PlaceCategory(id: 13, name: 'Шардаринский район'),
    ],
  ),
  PlaceCategory(
    id: 21,
    name: 'Улытауская область',
    subcategories: [
      PlaceCategory(id: 0, name: 'Жанааркинский район'),
      PlaceCategory(id: 1, name: 'Улытауский район'),
    ],
  ),
];
